export const MarkerData = [
  {
    position: {lat:  50.933722027336096, lng:  -114.08462126102336 } ,
    name: 'Fish Creek Parking Lot',
    description: 'It is the official starting and ending point for Fish Creek Votier Flats Trail. There is a comfortable restroom near the place. Lots of people group here and enjoy their weekend. Best time: anytime before night',
    category: 'anytime before night',
    iconid: '7',
    picture: './begin.jpg', 
  },
  {
    position: {lat: 50.92995480462546, lng:  -114.11547739481257},
    name: 'Restroom',
    description: 'Public restroom with bathroom',
    category: 'stunning_view',
    iconid: '0',
    picture: './restroom.jpg', 
  },
  {
    position: {lat: 50.9311940, lng:  -114.1035950},
    name: 'Grassy Small mud trail',
    description: 'You will experience the feeling of living in nature on this small trail. However, it also means you might need to do some mosquito protection. Please be in mind, here is quite easy to lose your way.',
    category: 'stunning_view',
    iconid: '4',
    picture: './sl1.png', 
  },
  {
    position: {lat:  50.9288380, lng: -114.1050950},
    name: 'Muddy roots small trail',
    description: 'This small trail is full of different types of flowers. It is a beautiful place for flower viewing. Please be aware of your steps while watching those flowers, the roots might get you stumble.',
    category: 'stunning_view',
    iconid: '3',
    picture: './sl2.jpg', 
  },
  {
    position: {lat:  50.934576, lng: -114.101750}, 
    name: 'The overview of the past trail',
    description: 'This path is the highest one on the trail. You are able to see all the trails you went on the path. The soil here is quite soft, so please be very careful while on the path.',
    category: 'stunning_view',
    iconid: '4',
    picture: './sl3.jpg', 
  },
  {
    position: {lat:  50.92951649460113, lng: -114.10819162775387},
    name: 'Stormwater Wet Pond',
    description: 'It is a huge pond with reeds, birds, frogs, ants, and fish. You might get a huge chance to have a really close experience with those livings. Be careful not to get too close to the pond in case you get stuck in the swampy.',
    category: 'stunning_view',
    iconid: '2',
    picture: './sl4.jpg', 
  },
  {
    position: {lat:  50.93353902928432, lng: -114.09266880696357},
    name: 'Second junction of the trail',
    description: 'This location is a great location to spot birds and bugs surrounding.',
    category: 'stunning_view',
    iconid: '2',
    picture: './sl5.jpg', 
  },
  {
    position: {lat:  50.9340860, lng: -114.1041030},
    name: 'Bridge roads of the trail',
    description: 'If you look further at the river, you might see some branches across the river. There will be the place Beaver lives.',
    category: 'stunning_view',
    iconid: '4',
    picture: './sl6.jpg', 
  }
];
